### ISSUE TITLE
Recent Discord update broke your plugin.

### ISSUE THREAD

**Issue by just-Addict** [awaken1ng/bd-linestickers#14] opened 2017-11-23 10:57 UTC
![2017-11-23_115417](https://user-images.githubusercontent.com/19715616/33169512-488b6054-d045-11e7-942c-e24e23ed7591.png)

After some digging I isolated this crash to your plugin.

**Comment by awaken1ng** [comment] 2017-11-26 12:49
Can't reproduce the error on stable nor canary. Judging by the traceback, something is with the configuration JSON in plugins folder, try deleting or moving it or look what's wrong at position 119, if you could upload it here for me to take a look at that would be great too.

**Comment by just-Addict** [comment] 2017-11-26 22:26
I checked the json file for the collection too, but the thing is, none of the entries even reach position 119, and this error only shows when I move the plugin into the folder, even without a configuration file present
 
 
-----Original Message-----

**Comment by just-Addict** [comment] 2017-11-26 22:28
I did notice one thing... none of the entries is getting a closing " after the title.
 
-----Original Message-----

**Closed as completed** 2018-02-07 12:20 UTC
